#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u https://github.com/StyxProject/manifest -b R -g default,-device,-mips,-darwin,-notdefault
git config --global user.name maade69
git config --global user.email p1nchp0d@bk.ru

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Sync stuffs
cd build/soong && git remote add d https://github.com/SyntatiX-OS/build_soong -f && git cherry-pick 781bd3afedb8891ddbeab6f96555db68ca1a2ad3^..470a3a74636831eb89f3c274897a1483761e9079 && cd ../..
git clone https://github.com/LineageOS/android_hardware_xiaomi.git --single-branch -b lineage-18.1 hardware/xiaomi --depth=1
git clone https://github.com/StyxProject-Devices/device_xiaomi_davinci.git --single-branch -b R device/xiaomi/davinci
git clone https://github.com/maade69/device_xiaomi_sm6150-common.git --single-branch -b styx device/xiaomi/sm6150-common
git clone https://github.com/vantoman/kernel_xiaomi_sm6150 --single-branch -b android11 kernel/xiaomi/sm6150
git clone https://github.com/xiaomi-sm6150/android_vendor_xiaomi --single-branch -b lineage-18.1 vendor/xiaomi 
